teste de model
raonircl/api-postgresql pull request #15
Opened 2022-10-19 12:37 UTC by raonircl

2022-10-19 14:11 UTC, joathan requested changes

2022-10-19 14:11 UTC, joathan commented on spec/models/user_spec.rb
> +end
isso não corresponde a tarefa: _criar um teste com rspec que faça validação dos campos obrigatórios name e age_

2022-10-19 14:11 UTC, joathan commented on spec/models/user_spec.rb
> +  it 'teste de validação' do
não se poe em pt-br

2022-10-19 14:11 UTC, joathan commented on spec/models/user_spec.rb
> +    #user = User.create(name: '', age: 0)
não se deixa comentario em codigo.

2022-10-19 14:11 UTC, joathan commented on spec/models/user_spec.rb
> +    expect(user).to ep " '' 0 "
o que isso faz?

2022-10-19 14:11 UTC, joathan commented on spec/models/user_spec.rb
> +    user = build(:user, name: '', age: 0)
isso nao precisa!

2022-10-20 14:08 UTC, joathan commented on spec/examples.txt
> +./spec/models/user_spec.rb[1:1:2] | passed | 0.01897 seconds |
o que é isso ?

2022-10-20 14:13 UTC, joathan commented on spec/spec_helper.rb
> +#=end
pra que serve isso?

2022-10-21 01:50 UTC, raonircl commented on spec/examples.txt
> +./spec/models/user_spec.rb[1:1:2] | passed | 0.01897 seconds |
Log de test

2022-10-24 21:51 UTC, joathan requested changes

2022-10-24 21:51 UTC, joathan commented on spec/models/user_spec.rb
> +#binding.pry
pra que isso ?

2022-10-24 22:13 UTC, raonircl commented on spec/models/user_spec.rb
> +#binding.pry
Ok

2022-10-25 01:03 UTC, joathan requested changes
o sistema ainda permite que o nome do Usr seja apenas uma unica Letra.
<img width="369" alt="Captura de Tela 2022-10-24 às 22 00 31" src="https://user-images.githubusercontent.com/8137319/197657926-43fa66b2-e55b-421b-9ace-04900478d407.png">
ou um unico caracter...
<img width="362" alt="Captura de Tela 2022-10-24 às 22 00 55" src="https://user-images.githubusercontent.com/8137319/197657945-62ef2ca0-570d-476f-b74d-bd61258be791.png">
vc precisa validar que o nome do User tenha ao menos 3 caracter ou uma silaba.

2022-10-25 01:03 UTC, joathan commented on spec/factories/users.rb
> +end
ja rodou os testes sem esse arquivo?

2022-10-25 01:03 UTC, joathan commented on spec/models/user_spec.rb
> +
não precisa dessa linha!

2022-10-25 04:49 UTC, raonircl commented on spec/factories/users.rb
> +end
Sim! Ele continua passando no teste sem a presença desse arquivo.

2022-10-25 04:56 UTC, raonircl commented on spec/models/user_spec.rb
> +
ok!

2022-10-28 18:45 UTC, joathan approved these changes

2022-10-29 16:05 UTC, merged